- name: Run Java
  ansible.builtin.include_role:
    name: common
    tasks_from: java

- name: Install MySQL
  ansible.builtin.dnf:
    name: mysql
    state: latest

- name: Load Schema
  ansible.builtin.shell: mysql -h mysql-dev.rahuldevops85.online -uroot -pChicago12345 < /app/db/schema.sql

- name: Load app-user
  ansible.builtin.shell: mysql -h mysql-dev.rahuldevops85.online -uroot -pChicago12345 < /app/db/app-user.sql

- name: Load master-data
  ansible.builtin.shell: mysql -h mysql-dev.rahuldevops85.online -uroot -pChicago12345 < /app/db/master-data.sql

- name: Run systemd_setup
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd_setup